name: Build and Upload Binaries

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write # To sign the provenance.
  contents: write # To upload assets to release.
  actions: read # To read the workflow path.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - amd64
          - arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - name: Set GOOS and GOARCH
        run: |
          echo "GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV    
      - name: Build ai-example
        working-directory: ./ai-example
        run: |
          BINARY_NAME="wk.plugin.ai-example-$GOOS-$GOARCH.wkp"
          go build -o $BINARY_NAME || exit 1

      - name: Build ai-volcengine
        working-directory: ./ai-volcengine
        run: |
          BINARY_NAME="wk.plugin.ai-volcengine-$GOOS-$GOARCH.wkp"
          go build -o $BINARY_NAME || exit 1

      - name: Build search
        working-directory: ./search
        run: |
          BINARY_NAME="wk.plugin.search-$GOOS-$GOARCH.wkp"
          go build -o $BINARY_NAME || exit 1

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./ai-example/wk.plugin.ai-example-*
            ./ai-volcengine/wk.plugin.ai-volcengine-*
            ./search/wk.plugin.search-*
  create-and-upload-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List Artifacts
        run: |
          ls -R ./artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: |
            ./artifacts/binaries-*/**/*.wkp